title: Bea De Oliveira
logo: webpic-modified.png
links:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/beadeoliveira"
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/beatriz-de-oliveira-3489a812a"
theme: jekyll-theme-minimal
