title: Bea De Oliveira
logo: file:///Users/beadeoliveira/Downloads/websitepic.pdf
description: **About me:**
I am an undergraduate student and A.B. Duke Scholar at Duke University pursuing a double major in Computational Economics and German. I am passionate about the possibilities of the integration of economics and computer science in business and development.
theme: jekyll-theme-minimal
